import React from 'react';

function About() {
  return (
    <div className="bg-gray-100 p-8">
      <div className="max-w-2xl mx-auto">
        <h1 className="text-3xl font-bold mb-4">About</h1>

        <p className="mb-4">
          Welcome to our hashing website! We offer a unique approach to password security that allows you to use hash
          digests as your passwords. With our service, you can create strong and secure passwords in a way that is both
          easy to remember and highly resistant to unauthorized access.
        </p>

        <h2 className="text-xl font-bold mb-2">Using Hash Digests for Passwords</h2>

        <p className="mb-4">
          Traditionally, creating and remembering complex passwords can be a challenging task. However, by using hash
          digests, you can simplify this process while ensuring the security of your accounts.
        </p>

        <p className="mb-4">
          A hash digest is a unique, fixed-length string generated by applying a hashing algorithm to your original
          password. The resulting hash digest serves as a representation of your password, but it cannot be reversed or
          decrypted to retrieve the original password.
        </p>

        <h2 className="text-xl font-bold mb-2">Advantages of Hash Digests as Passwords</h2>

        <ul className="list-disc pl-6 mb-4">
          <li>
            <strong>Enhanced Security:</strong> Hash digests provide a high level of security because they are not
            susceptible to password cracking techniques. Even if an attacker gains access to the hash digest, it is
            extremely difficult to determine the original password.
          </li>
          <li>
            <strong>Simplicity:</strong> Hash digests are often shorter and easier to remember compared to complex
            passwords. You can generate a hash digest from a passphrase or a combination of memorable words, making it
            easier for you to recall and use your passwords across different platforms.
          </li>
          <li>
            <strong>Unique Passwords:</strong> Since each hash digest is unique, even if you use the same passphrase or
            words, the resulting hash digests will be different for each account. This ensures that your passwords
            remain unique and reduces the risk of password reuse vulnerabilities.
          </li>
        </ul>

        <h2 className="text-xl font-bold mb-2">How to Use Hash Digests as Passwords</h2>

        <ol className="list-decimal pl-6 mb-4">
          <li>
            Choose a passphrase or a combination of words that are meaningful to you and easy to remember.
          </li>
          <li>Use our hashing service to generate a hash digest from your chosen passphrase or words.</li>
          <li>
            When prompted for a password on a website or application, enter the corresponding hash digest instead of the
            original passphrase.
          </li>
          <li>
            Our system will validate the hash digest against the stored hash, ensuring a secure and seamless
            authentication process.
          </li>
        </ol>

        <p>
          Remember to keep your passphrase or words confidential and avoid sharing them with others. This way, you can
          leverage the benefits of hash digests while maintaining the security of your accounts.
        </p>
      </div>
    </div>
  );
}

export default About;
